package Bagian_12;

public class Percobaan extends Exception {
    private String Teks;
    Percobaan(String s)
    {
        Teks="Excaption generated by: "+s;
        System.out.println(Teks);
    }
}
class Eksepsi {
    static void tampil(String s) throws Exception
    {
        System.out.println("Tampil");
        if(s.equals("Ranggis"))
        {
            throw new Percobaan(s);
        }
        System.out.println("OK!");
    }
    public static void main(String[] args) throws Exception {
        try
        {
            tampil("ali");
            tampil("Ranggis");
        }
        catch(Percobaan ex)
        {
            System.out.println("Tangkap: "+ex);
        }
    }
}
